const AMENITIES = {
  WIFI: "WIFI",
  COFFEE: "COFFEE",
  PARKING: "PARKING",
  PRINTER: "PRINTER",
  MONITOR: "MONITOR",
  PHONE: "PHONE",

  MEETING_ROOM: "MEETING_ROOM",
  PRIVATE_ROOM: "PRIVATE_ROOM",
  OPEN_SPACE: "OPEN_SPACE",
  INDIVIDUAL_DESK: "INDIVIDUAL_DESK",

  FLEX_HOURS: "FLEX_HOURS",
  AIR_CONDITIONING: "AIR_CONDITIONING",
  NATURAL_LIGHT: "NATURAL_LIGHT",

  POWER_OUTLETS: "POWER_OUTLETS",
  SECURITY: "SECURITY",
  CAMERAS: "CAMERAS",
  LOCKERS: "LOCKERS",

  ACCESSIBILITY: "ACCESSIBILITY",
};

module.exports = { AMENITIES };
